### ISSUE TITLE
DevWorkspace 0.8.0 Final Checklist

### ISSUE THREAD

**Issue by JPinkney** [devfile/devworkspace-operator#518]
List of PR's that should be in the first release:
- [x] https://github.com/devfile/devworkspace-operator/pull/495
- [x] https://github.com/devfile/devworkspace-operator/pull/509
- [x] https://github.com/devfile/devworkspace-operator/pull/519
- [x] https://github.com/devfile/devworkspace-operator/pull/521
- [x] https://github.com/devfile/devworkspace-operator/pull/522

List of PR's that _might_ need to come in for the first release:
- [x] https://github.com/devfile/devworkspace-operator/pull/538
- [x] https://github.com/devfile/devworkspace-operator/pull/500
- [x] https://github.com/devfile/devworkspace-operator/pull/504

Timeline:
- Che 7.34 28 July
- [WTO 1.3](https://issues.redhat.com/browse/WTO/fixforversion/12353287) 10 Aug
- [CRW 2.11](https://issues.redhat.com/browse/CRW/fixforversion/12356458) Sep 07

**Comment by amisevsk** [comment]
I've made a late addition of https://github.com/devfile/devworkspace-operator/pull/529 -- it's required depending on whether we're planning on pushing DWO 1.0 onto the developer sandbox. If we don't expect to make the switch to devfile 2.0 there before DWO 1.1 is released, it can safely be ignored for now.

**Comment by sleshchenko** [comment]
So, due a fact that Che DevWorkspace servers don't have authentication yet, CRW 2.11 won't enabled devworkspace support on DevSandbox, so workspaceEnv is out of the DWO 0.8.0 release scope.
Everything needs should be already included, DWO 0.8.0 should happen this week

**Comment by sleshchenko** [comment]
DWO 0.8 is alive
